data:
  augmentation:
    photometric:
      enable: false
  dataset: Coco
  export_folder: val
  gaussian_label:
    enable: false
    sigma: 1.0
  homography_adaptation:
    aggregation: sum
    enable: true
    filter_counts: 0
    homographies:
      params:
        allow_artifacts: true
        patch_ratio: 0.85
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
    num: 100
  preprocessing:
    resize:
    - 240
    - 320
model:
  batch_size: 1
  detection_threshold: 0.015
  eval_batch_size: 1
  name: SuperPointNet_gauss2
  nms: 4
  params: {}
  subpixel:
    enable: false
  top_k: 600
pretrained: /data/projects/pixelplus/pytorch-superpoint/logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar
training:
  workers_test: 2
